#!/usr/bin/env bash
#debugging nginx port 80
#How I solved it: delete the exeisting ../sites-enabled/defualt and replace it with a copy of
# ../sites-available/defualt. you do that by creating a symbolic link.
#NB: The flag -s creates a symbolic link, -f deletes the existing file and replaces it 
sudo in -sf /etc/nginx/sites-available/default /etc/nginx/sites-enable/default
sudo service nginx restart

