#!/usr/bin/env bash 
#configures an Nginx server to listen on port 80. 
In -sf /etc/nginx/sites-0available/default /etcnginx/site-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
