#!/usr/bin/env bash
# display corresponding text using case statement
w=1
while [ $w -lt 21 ];
do
	echo "$w"
	case $w in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((w++))
done
