#!/usr/bin/env bash
# run apache on designated containers

sudo apt-get -y update
sudo apt-gate -y install apache2
sudo /etc/init.d/apache2 start
echo "Hello Holberton" | sudo tee -a /var/www/html/index.html
sudo /etc/init.d/apache2 restart
